homeassistant_service_group:
  id: service_group_component
  commands:
    - text: "Feed monster"
      command:
        - homeassistant.service:
            service: button.press
            data:
              entity_id: "button.catfeeder_d1_feed_single"
    - text: "desk down"
      command:
        - lambda: |-
            ESP_LOGI("homeassistant_service_group", "down");
        - homeassistant.service:
            service: script.set_desk_height
            data:
              height: "low"
    - text: "desk up"
      command:
        - lambda: |-
            ESP_LOGI("homeassistant_service_group", "up");
        - homeassistant.service:
            service: script.set_desk_height
            data:
              height: "high"
    - text: "desk nudge up"
      command:
        - lambda: |-
            ESP_LOGI("homeassistant_service_group", "nudge up");
        - homeassistant.service:
            service: button.press
            data:
              entity_id: "button.desk_position_nudge_up"
    - text: "desk nudge down"
      command:
        - lambda: |-
            ESP_LOGI("homeassistant_service_group", "nudge down");
        - homeassistant.service:
            service: button.press
            data:
              entity_id: "button.desk_position_nudge_down"
    - text: "color lights"
      command:
        - homeassistant.service:
            service: script.colors
    - text: "hell lights"
      command:
        - homeassistant.service:
            service: scene.turn_on
            data:
              entity_id: "scene.hell"
    - text: "lights off"
      command:
        - homeassistant.service:
            service: script.off_script